### ISSUE TITLE
option for upload-adapter

### ISSUE THREAD

**Issue by selbest** [jainsuneet/ckeditor5-build-classic-extended#3]
It is very lucky fro me to find this package of ckeditor that satisfies 99% needs of our project.
But in our  situations,  we need to upload file to remote server, and this package upload file by base64-adapter instead.
So set option for editor when instance created to decide upload-adapter type.

The uploaderAdapter [is commented out](https://github.com/jainsuneet/ckeditor5-build-classic-extended/blob/master/src/ckeditor.js#L10). Do you have plan to make upload-adapter type option come true :)

**Comment by jainsuneet** [comment]
> It is very lucky fro me to find this package of ckeditor that satisfies 99% needs of our project.
> But in our situations, we need to upload file to remote server, and this package upload file by base64-adapter instead.
> So set option for editor when instance created to decide upload-adapter type.
> 
> The uploaderAdapter [is commented out](https://github.com/jainsuneet/ckeditor5-build-classic-extended/blob/master/src/ckeditor.js#L10). Do you have plan to make upload-adapter type option come true :)

I will enable the UploadAdapter and publish a new version.

**Comment by jainsuneet** [comment]
> It is very lucky fro me to find this package of ckeditor that satisfies 99% needs of our project.
> But in our situations, we need to upload file to remote server, and this package upload file by base64-adapter instead.
> So set option for editor when instance created to decide upload-adapter type.
> 
> The uploaderAdapter [is commented out](https://github.com/jainsuneet/ckeditor5-build-classic-extended/blob/master/src/ckeditor.js#L10). Do you have plan to make upload-adapter type option come true :)

The [uploaderAdapter](https://github.com/jainsuneet/ckeditor5-build-classic-extended/blob/master/src/ckeditor.js#L10) is specifically for ckfinder. 

You can define a [custom uploader](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/upload-adapter.html#the-anatomy-of-the-adapter) directly using the editor ready event as it gives more control or use the [Simple Upload Adapter](https://ckeditor.com/docs/ckeditor5/latest/features/image-upload/simple-upload-adapter.html). I have now also enabled Simple Upload Adapter.

**Comment by selbest** [comment]
> > It is very lucky fro me to find this package of ckeditor that satisfies 99% needs of our project.
> > But in our situations, we need to upload file to remote server, and this package upload file by base64-adapter instead.
> > So set option for editor when instance created to decide upload-adapter type.
> > The uploaderAdapter [is commented out](https://github.com/jainsuneet/ckeditor5-build-classic-extended/blob/master/src/ckeditor.js#L10). Do you have plan to make upload-adapter type option come true :)
> 
> The [uploaderAdapter](https://github.com/jainsuneet/ckeditor5-build-classic-extended/blob/master/src/ckeditor.js#L10) is specifically for ckfinder.
> 
> You can define a [custom uploader](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/upload-adapter.html#the-anatomy-of-the-adapter) directly using the editor ready event as it gives more control or use the [Simple Upload Adapter](https://ckeditor.com/docs/ckeditor5/latest/features/image-upload/simple-upload-adapter.html). I have now also enabled Simple Upload Adapter.

It's so kind of you.Thanks a lot.
 Custom uploader it depends on uploaderAdapter.Define a custom uploader the uploaderAdapter should be imported.
